#!/usr/bin/env zsh

# Use Neovim as "preferred editor"​
export VISUAL=nvim
export EDITOR=nvim

# Enable persistent REPL history for `node`.
export NODE_REPL_HISTORY_FILE=~/.node_history;
export NODE_REPL_HISTORY_SIZE='50000';

export HISTSIZE=1000000;
export SAVEHIST=$HISTSIZE;
export HISTFILESIZE="${HISTSIZE}";
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth';

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

export GPG_TTY=$(tty);

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# Add mysql@5.7 to PATH
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"

export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# For linux paths
export PATH="/home/aaronmak/.local/bin:$PATH"

export DISABLE_TELEMETRY=1
export DISABLE_ERROR_REPORTING=1
