name: dev
root: ~/code/personal/

windows:
  - haskell:
      root: ~/code/personal/haskell-book-exercises
      layout: main-vertical
      panes:
        - vim
        -
        -
  - qwiser:
      root: ~/code/personal/qwiser
      layout: main-vertical
      panes:
        - vim
        -
        -
