name: config
root: ~/code/personal/

windows:
  - dotfiles:
      root: ~/code/personal/dotfiles/
      layout: main-vertical
      panes:
        - vim
        -
  - mac-setup:
      root: ~/code/personal/mac-setup/
      layout: main-vertical
      panes:
        - vim
        -
  - snippets:
      root: ~/code/personal/snippets/
      layout: main-vertical
      panes:
        - vim
        -
